FROM node:18
ARG MONGODB_URI
ARG PRIVATE_KEY
ARG ENV
ARG GREGG_CLIENT_ID
ARG GREGG_CLIENT_SECRET
ENV MONGODB_URI=$MONGODB_URI
ENV PRIVATE_KEY=$PRIVATE_KEY
ENV ENV $ENV
ENV GREGG_CLIENT_ID=$GREGG_CLIENT_ID
ENV GREGG_CLIENT_SECRET=$GREGG_CLIENT_SECRET
WORKDIR /ows
COPY package*.json ./
COPY . .
RUN yarn install
RUN yarn run build
EXPOSE 8080
CMD ["yarn", "start:prod"]