/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateEventDto } from '../models';
// @ts-ignore
import { EventDocument } from '../models';
// @ts-ignore
import { UpdateEventDto } from '../models';
/**
 * EventsApi - axios parameter creator
 * @export
 */
export const EventsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerCreate: async (createEventDto: CreateEventDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createEventDto' is not null or undefined
            assertParamExists('eventsControllerCreate', 'createEventDto', createEventDto)
            const localVarPath = `/api/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} url 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerCreateFromUrl: async (url: string, createEventDto: CreateEventDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'url' is not null or undefined
            assertParamExists('eventsControllerCreateFromUrl', 'url', url)
            // verify required parameter 'createEventDto' is not null or undefined
            assertParamExists('eventsControllerCreateFromUrl', 'createEventDto', createEventDto)
            const localVarPath = `/api/events/{url}`
                .replace(`{${"url"}}`, encodeURIComponent(String(url)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [name] The name of the event.
         * @param {string} [bookSearchQuery] The query string which will search among book titles.
         * @param {Array<string>} [bookIds] A list of object IDs pointing to book documents.
         * @param {Array<string>} [threads] A list of channel/thread IDs.
         * @param {'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled'} [status] The status of the event.
         * @param {'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other'} [type] The type of the event.
         * @param {string} [startDateBefore] The start date of the event should be before this date.
         * @param {string} [startDateAfter] The start date of the event should be after this date.
         * @param {string} [endDateBefore] The end date of the event should be before this date.
         * @param {string} [endDateAfter] The end date of the event should be after this date.
         * @param {Array<string>} [participantIds] The ID of the participant of the event should be in this list. This covers requestors, interested, readers etc all participants.
         * @param {Array<string>} [requestedByIds] The ID of the requestor of the event should be in this list.
         * @param {Array<string>} [interestedIds] The ID of the interested people of the event should be in this list.
         * @param {Array<string>} [readerIds] The ID of the reader of the event should be in this list.
         * @param {Array<string>} [leaderIds] The ID of the leader of the event should be in this list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerFind: async (name?: string, bookSearchQuery?: string, bookIds?: Array<string>, threads?: Array<string>, status?: 'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled', type?: 'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other', startDateBefore?: string, startDateAfter?: string, endDateBefore?: string, endDateAfter?: string, participantIds?: Array<string>, requestedByIds?: Array<string>, interestedIds?: Array<string>, readerIds?: Array<string>, leaderIds?: Array<string>, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/events`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (bookSearchQuery !== undefined) {
                localVarQueryParameter['bookSearchQuery'] = bookSearchQuery;
            }

            if (bookIds) {
                localVarQueryParameter['bookIds'] = bookIds;
            }

            if (threads) {
                localVarQueryParameter['threads'] = threads;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            if (type !== undefined) {
                localVarQueryParameter['type'] = type;
            }

            if (startDateBefore !== undefined) {
                localVarQueryParameter['startDateBefore'] = (startDateBefore as any instanceof Date) ?
                    (startDateBefore as any).toISOString() :
                    startDateBefore;
            }

            if (startDateAfter !== undefined) {
                localVarQueryParameter['startDateAfter'] = (startDateAfter as any instanceof Date) ?
                    (startDateAfter as any).toISOString() :
                    startDateAfter;
            }

            if (endDateBefore !== undefined) {
                localVarQueryParameter['endDateBefore'] = (endDateBefore as any instanceof Date) ?
                    (endDateBefore as any).toISOString() :
                    endDateBefore;
            }

            if (endDateAfter !== undefined) {
                localVarQueryParameter['endDateAfter'] = (endDateAfter as any instanceof Date) ?
                    (endDateAfter as any).toISOString() :
                    endDateAfter;
            }

            if (participantIds) {
                localVarQueryParameter['participantIds'] = participantIds;
            }

            if (requestedByIds) {
                localVarQueryParameter['requestedByIds'] = requestedByIds;
            }

            if (interestedIds) {
                localVarQueryParameter['interestedIds'] = interestedIds;
            }

            if (readerIds) {
                localVarQueryParameter['readerIds'] = readerIds;
            }

            if (leaderIds) {
                localVarQueryParameter['leaderIds'] = leaderIds;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerFindOne: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('eventsControllerFindOne', 'id', id)
            const localVarPath = `/api/events/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerRemove: async (id: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('eventsControllerRemove', 'id', id)
            const localVarPath = `/api/events/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerUpdate: async (id: string, updateEventDto: UpdateEventDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('eventsControllerUpdate', 'id', id)
            // verify required parameter 'updateEventDto' is not null or undefined
            assertParamExists('eventsControllerUpdate', 'updateEventDto', updateEventDto)
            const localVarPath = `/api/events/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateEventDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EventsApi - functional programming interface
 * @export
 */
export const EventsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EventsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerCreate(createEventDto: CreateEventDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDocument>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerCreate(createEventDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} url 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerCreateFromUrl(url: string, createEventDto: CreateEventDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDocument>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerCreateFromUrl(url, createEventDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} [name] The name of the event.
         * @param {string} [bookSearchQuery] The query string which will search among book titles.
         * @param {Array<string>} [bookIds] A list of object IDs pointing to book documents.
         * @param {Array<string>} [threads] A list of channel/thread IDs.
         * @param {'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled'} [status] The status of the event.
         * @param {'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other'} [type] The type of the event.
         * @param {string} [startDateBefore] The start date of the event should be before this date.
         * @param {string} [startDateAfter] The start date of the event should be after this date.
         * @param {string} [endDateBefore] The end date of the event should be before this date.
         * @param {string} [endDateAfter] The end date of the event should be after this date.
         * @param {Array<string>} [participantIds] The ID of the participant of the event should be in this list. This covers requestors, interested, readers etc all participants.
         * @param {Array<string>} [requestedByIds] The ID of the requestor of the event should be in this list.
         * @param {Array<string>} [interestedIds] The ID of the interested people of the event should be in this list.
         * @param {Array<string>} [readerIds] The ID of the reader of the event should be in this list.
         * @param {Array<string>} [leaderIds] The ID of the leader of the event should be in this list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerFind(name?: string, bookSearchQuery?: string, bookIds?: Array<string>, threads?: Array<string>, status?: 'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled', type?: 'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other', startDateBefore?: string, startDateAfter?: string, endDateBefore?: string, endDateAfter?: string, participantIds?: Array<string>, requestedByIds?: Array<string>, interestedIds?: Array<string>, readerIds?: Array<string>, leaderIds?: Array<string>, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<EventDocument>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerFind(name, bookSearchQuery, bookIds, threads, status, type, startDateBefore, startDateAfter, endDateBefore, endDateAfter, participantIds, requestedByIds, interestedIds, readerIds, leaderIds, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerFindOne(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDocument>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerFindOne(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerRemove(id: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerRemove(id, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async eventsControllerUpdate(id: string, updateEventDto: UpdateEventDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EventDocument>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.eventsControllerUpdate(id, updateEventDto, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * EventsApi - factory interface
 * @export
 */
export const EventsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EventsApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerCreate(createEventDto: CreateEventDto, options?: any): AxiosPromise<EventDocument> {
            return localVarFp.eventsControllerCreate(createEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} url 
         * @param {CreateEventDto} createEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerCreateFromUrl(url: string, createEventDto: CreateEventDto, options?: any): AxiosPromise<EventDocument> {
            return localVarFp.eventsControllerCreateFromUrl(url, createEventDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [name] The name of the event.
         * @param {string} [bookSearchQuery] The query string which will search among book titles.
         * @param {Array<string>} [bookIds] A list of object IDs pointing to book documents.
         * @param {Array<string>} [threads] A list of channel/thread IDs.
         * @param {'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled'} [status] The status of the event.
         * @param {'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other'} [type] The type of the event.
         * @param {string} [startDateBefore] The start date of the event should be before this date.
         * @param {string} [startDateAfter] The start date of the event should be after this date.
         * @param {string} [endDateBefore] The end date of the event should be before this date.
         * @param {string} [endDateAfter] The end date of the event should be after this date.
         * @param {Array<string>} [participantIds] The ID of the participant of the event should be in this list. This covers requestors, interested, readers etc all participants.
         * @param {Array<string>} [requestedByIds] The ID of the requestor of the event should be in this list.
         * @param {Array<string>} [interestedIds] The ID of the interested people of the event should be in this list.
         * @param {Array<string>} [readerIds] The ID of the reader of the event should be in this list.
         * @param {Array<string>} [leaderIds] The ID of the leader of the event should be in this list.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerFind(name?: string, bookSearchQuery?: string, bookIds?: Array<string>, threads?: Array<string>, status?: 'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled', type?: 'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other', startDateBefore?: string, startDateAfter?: string, endDateBefore?: string, endDateAfter?: string, participantIds?: Array<string>, requestedByIds?: Array<string>, interestedIds?: Array<string>, readerIds?: Array<string>, leaderIds?: Array<string>, options?: any): AxiosPromise<Array<EventDocument>> {
            return localVarFp.eventsControllerFind(name, bookSearchQuery, bookIds, threads, status, type, startDateBefore, startDateAfter, endDateBefore, endDateAfter, participantIds, requestedByIds, interestedIds, readerIds, leaderIds, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerFindOne(id: string, options?: any): AxiosPromise<EventDocument> {
            return localVarFp.eventsControllerFindOne(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerRemove(id: string, options?: any): AxiosPromise<boolean> {
            return localVarFp.eventsControllerRemove(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} id 
         * @param {UpdateEventDto} updateEventDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        eventsControllerUpdate(id: string, updateEventDto: UpdateEventDto, options?: any): AxiosPromise<EventDocument> {
            return localVarFp.eventsControllerUpdate(id, updateEventDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EventsApi - object-oriented interface
 * @export
 * @class EventsApi
 * @extends {BaseAPI}
 */
export class EventsApi extends BaseAPI {
    /**
     * 
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerCreate(createEventDto: CreateEventDto, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerCreate(createEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} url 
     * @param {CreateEventDto} createEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerCreateFromUrl(url: string, createEventDto: CreateEventDto, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerCreateFromUrl(url, createEventDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [name] The name of the event.
     * @param {string} [bookSearchQuery] The query string which will search among book titles.
     * @param {Array<string>} [bookIds] A list of object IDs pointing to book documents.
     * @param {Array<string>} [threads] A list of channel/thread IDs.
     * @param {'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled'} [status] The status of the event.
     * @param {'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other'} [type] The type of the event.
     * @param {string} [startDateBefore] The start date of the event should be before this date.
     * @param {string} [startDateAfter] The start date of the event should be after this date.
     * @param {string} [endDateBefore] The end date of the event should be before this date.
     * @param {string} [endDateAfter] The end date of the event should be after this date.
     * @param {Array<string>} [participantIds] The ID of the participant of the event should be in this list. This covers requestors, interested, readers etc all participants.
     * @param {Array<string>} [requestedByIds] The ID of the requestor of the event should be in this list.
     * @param {Array<string>} [interestedIds] The ID of the interested people of the event should be in this list.
     * @param {Array<string>} [readerIds] The ID of the reader of the event should be in this list.
     * @param {Array<string>} [leaderIds] The ID of the leader of the event should be in this list.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerFind(name?: string, bookSearchQuery?: string, bookIds?: Array<string>, threads?: Array<string>, status?: 'Requested' | 'Approved' | 'Announced' | 'Ongoing' | 'Completed' | 'Rejected' | 'Cancelled', type?: 'BuddyRead' | 'MonthlyRead' | 'ShortStoryRead' | 'PoetryRead' | 'Other', startDateBefore?: string, startDateAfter?: string, endDateBefore?: string, endDateAfter?: string, participantIds?: Array<string>, requestedByIds?: Array<string>, interestedIds?: Array<string>, readerIds?: Array<string>, leaderIds?: Array<string>, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerFind(name, bookSearchQuery, bookIds, threads, status, type, startDateBefore, startDateAfter, endDateBefore, endDateAfter, participantIds, requestedByIds, interestedIds, readerIds, leaderIds, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerFindOne(id: string, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerFindOne(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerRemove(id: string, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerRemove(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} id 
     * @param {UpdateEventDto} updateEventDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EventsApi
     */
    public eventsControllerUpdate(id: string, updateEventDto: UpdateEventDto, options?: AxiosRequestConfig) {
        return EventsApiFp(this.configuration).eventsControllerUpdate(id, updateEventDto, options).then((request) => request(this.axios, this.basePath));
    }
}
