/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { BookDto } from '../models';
// @ts-ignore
import { GoodreadsBookDto } from '../models';
/**
 * GoodreadsApi - axios parameter creator
 * @export
 */
export const GoodreadsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerGetQuotes: async (q: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('goodreadsControllerGetQuotes', 'q', q)
            const localVarPath = `/api/goodreads/quotes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerSearchAndGetBook: async (q: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('goodreadsControllerSearchAndGetBook', 'q', q)
            const localVarPath = `/api/goodreads/book`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} q 
         * @param {number} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerSearchBooks: async (q: string, k: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'q' is not null or undefined
            assertParamExists('goodreadsControllerSearchBooks', 'q', q)
            // verify required parameter 'k' is not null or undefined
            assertParamExists('goodreadsControllerSearchBooks', 'k', k)
            const localVarPath = `/api/goodreads/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (q !== undefined) {
                localVarQueryParameter['q'] = q;
            }

            if (k !== undefined) {
                localVarQueryParameter['k'] = k;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GoodreadsApi - functional programming interface
 * @export
 */
export const GoodreadsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GoodreadsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goodreadsControllerGetQuotes(q: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goodreadsControllerGetQuotes(q, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goodreadsControllerSearchAndGetBook(q: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GoodreadsBookDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goodreadsControllerSearchAndGetBook(q, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @param {string} q 
         * @param {number} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async goodreadsControllerSearchBooks(q: string, k: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BookDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.goodreadsControllerSearchBooks(q, k, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * GoodreadsApi - factory interface
 * @export
 */
export const GoodreadsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GoodreadsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerGetQuotes(q: string, options?: any): AxiosPromise<Array<string>> {
            return localVarFp.goodreadsControllerGetQuotes(q, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} q 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerSearchAndGetBook(q: string, options?: any): AxiosPromise<GoodreadsBookDto> {
            return localVarFp.goodreadsControllerSearchAndGetBook(q, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} q 
         * @param {number} k 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        goodreadsControllerSearchBooks(q: string, k: number, options?: any): AxiosPromise<Array<BookDto>> {
            return localVarFp.goodreadsControllerSearchBooks(q, k, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GoodreadsApi - object-oriented interface
 * @export
 * @class GoodreadsApi
 * @extends {BaseAPI}
 */
export class GoodreadsApi extends BaseAPI {
    /**
     * 
     * @param {string} q 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoodreadsApi
     */
    public goodreadsControllerGetQuotes(q: string, options?: AxiosRequestConfig) {
        return GoodreadsApiFp(this.configuration).goodreadsControllerGetQuotes(q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} q 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoodreadsApi
     */
    public goodreadsControllerSearchAndGetBook(q: string, options?: AxiosRequestConfig) {
        return GoodreadsApiFp(this.configuration).goodreadsControllerSearchAndGetBook(q, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} q 
     * @param {number} k 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GoodreadsApi
     */
    public goodreadsControllerSearchBooks(q: string, k: number, options?: AxiosRequestConfig) {
        return GoodreadsApiFp(this.configuration).goodreadsControllerSearchBooks(q, k, options).then((request) => request(this.axios, this.basePath));
    }
}
