/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuthorDto
 */
export interface AuthorDto {
    /**
     * The name of the author.
     * @type {string}
     * @memberof AuthorDto
     */
    'name': string;
    /**
     * The GR/SG link to that author\'s page.
     * @type {string}
     * @memberof AuthorDto
     */
    'url': string;
}

