/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthorDto } from './author-dto';

/**
 * 
 * @export
 * @interface BookDto
 */
export interface BookDto {
    /**
     * The title of the book.
     * @type {string}
     * @memberof BookDto
     */
    'title': string;
    /**
     * A list of Author DTOs.
     * @type {Array<AuthorDto>}
     * @memberof BookDto
     */
    'authors': Array<AuthorDto>;
    /**
     * The GR/SG link to the book page.
     * @type {string}
     * @memberof BookDto
     */
    'url': string;
    /**
     * The list of genres for the book.
     * @type {Array<string>}
     * @memberof BookDto
     */
    'genres': Array<string>;
}

