/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ProfileDto } from './profile-dto';

/**
 * @type CreateUserDtoProfile
 * The profile information fot the user.
 * @export
 */
export type CreateUserDtoProfile = ProfileDto;


