/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateEventDtoDates } from './create-event-dto-dates';
// May contain unused imports in some cases
// @ts-ignore
import { CreateEventDtoRequestedBy } from './create-event-dto-requested-by';
// May contain unused imports in some cases
// @ts-ignore
import { Participant } from './participant';

/**
 * 
 * @export
 * @interface CreateEventDto
 */
export interface CreateEventDto {
    /**
     * The name of the event.
     * @type {string}
     * @memberof CreateEventDto
     */
    'name': string;
    /**
     * The object ID of the book document.
     * @type {string}
     * @memberof CreateEventDto
     */
    'book': string;
    /**
     * A list of channel/thread IDs.
     * @type {Array<string>}
     * @memberof CreateEventDto
     */
    'threads': Array<string>;
    /**
     * The status of the event.
     * @type {string}
     * @memberof CreateEventDto
     */
    'status': CreateEventDtoStatusEnum;
    /**
     * The type of the event.
     * @type {string}
     * @memberof CreateEventDto
     */
    'type': CreateEventDtoTypeEnum;
    /**
     * 
     * @type {CreateEventDtoDates}
     * @memberof CreateEventDto
     */
    'dates': CreateEventDtoDates;
    /**
     * 
     * @type {CreateEventDtoRequestedBy}
     * @memberof CreateEventDto
     */
    'requestedBy': CreateEventDtoRequestedBy;
    /**
     * A list of participants who show interest in the event.
     * @type {Array<Participant>}
     * @memberof CreateEventDto
     */
    'interested': Array<Participant>;
    /**
     * The participants who read the book in the event duration.
     * @type {Array<Participant>}
     * @memberof CreateEventDto
     */
    'readers': Array<Participant>;
    /**
     * The participants who lead the discussion for the event.
     * @type {Array<Participant>}
     * @memberof CreateEventDto
     */
    'leaders': Array<Participant>;
    /**
     * The description of the event.
     * @type {string}
     * @memberof CreateEventDto
     */
    'description': string;
}

export const CreateEventDtoStatusEnum = {
    Requested: 'Requested',
    Approved: 'Approved',
    Announced: 'Announced',
    Ongoing: 'Ongoing',
    Completed: 'Completed',
    Rejected: 'Rejected',
    Cancelled: 'Cancelled'
} as const;

export type CreateEventDtoStatusEnum = typeof CreateEventDtoStatusEnum[keyof typeof CreateEventDtoStatusEnum];
export const CreateEventDtoTypeEnum = {
    BuddyRead: 'BuddyRead',
    MonthlyRead: 'MonthlyRead',
    ShortStoryRead: 'ShortStoryRead',
    PoetryRead: 'PoetryRead',
    Other: 'Other'
} as const;

export type CreateEventDtoTypeEnum = typeof CreateEventDtoTypeEnum[keyof typeof CreateEventDtoTypeEnum];


