/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Participant } from './participant';

/**
 * @type CreateEventDtoRequestedBy
 * The participant who requested the event.
 * @export
 */
export type CreateEventDtoRequestedBy = Participant;


