/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DateRange
 */
export interface DateRange {
    /**
     * The start date of the event.
     * @type {string}
     * @memberof DateRange
     */
    'startDate': string;
    /**
     * The end date of the event.
     * @type {string}
     * @memberof DateRange
     */
    'endDate': string;
}

