/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthorDto } from './author-dto';
// May contain unused imports in some cases
// @ts-ignore
import { Book } from './book';

/**
 * @type EventDocumentBook
 * The book for which the event is happening.
 * @export
 */
export type EventDocumentBook = Book;


