/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthorDto } from './author-dto';

/**
 * 
 * @export
 * @interface GoodreadsBookDto
 */
export interface GoodreadsBookDto {
    /**
     * The title of the book.
     * @type {string}
     * @memberof GoodreadsBookDto
     */
    'title': string;
    /**
     * A list of Author DTOs.
     * @type {Array<AuthorDto>}
     * @memberof GoodreadsBookDto
     */
    'authors': Array<AuthorDto>;
    /**
     * The GR/SG link to the book page.
     * @type {string}
     * @memberof GoodreadsBookDto
     */
    'url': string;
    /**
     * The list of genres for the book.
     * @type {Array<string>}
     * @memberof GoodreadsBookDto
     */
    'genres': Array<string>;
    /**
     * The name of the series, if the book belongs to any.
     * @type {string}
     * @memberof GoodreadsBookDto
     */
    'series': string;
    /**
     * The GR link to the cover of the book.
     * @type {string}
     * @memberof GoodreadsBookDto
     */
    'coverUrl': string;
    /**
     * The average rating of the book.
     * @type {number}
     * @memberof GoodreadsBookDto
     */
    'avgRating': number;
    /**
     * The total number of ratings for the book.
     * @type {number}
     * @memberof GoodreadsBookDto
     */
    'numRatings': number;
    /**
     * The total number of reviews for the book.
     * @type {number}
     * @memberof GoodreadsBookDto
     */
    'numReviews': number;
    /**
     * The description or blurb of the book.
     * @type {string}
     * @memberof GoodreadsBookDto
     */
    'description': string;
    /**
     * The number of pages of the book.
     * @type {number}
     * @memberof GoodreadsBookDto
     */
    'numPages': number;
}

