/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Participant
 */
export interface Participant {
    /**
     * The object ID of the user (not the user ID).
     * @type {string}
     * @memberof Participant
     */
    'user': string;
    /**
     * The number of points to be assigned to the particpant.
     * @type {number}
     * @memberof Participant
     */
    'points': number;
}

