/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface QuestionAnswerDto
 */
export interface QuestionAnswerDto {
    /**
     * The question on the book page.
     * @type {string}
     * @memberof QuestionAnswerDto
     */
    'question': string;
    /**
     * The answer for the question on the book page.
     * @type {string}
     * @memberof QuestionAnswerDto
     */
    'answer': string;
}

