/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { AuthorDto } from './author-dto';
// May contain unused imports in some cases
// @ts-ignore
import { QuestionAnswerDto } from './question-answer-dto';

/**
 * 
 * @export
 * @interface StorygraphBookDto
 */
export interface StorygraphBookDto {
    /**
     * The title of the book.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'title': string;
    /**
     * A list of Author DTOs.
     * @type {Array<AuthorDto>}
     * @memberof StorygraphBookDto
     */
    'authors': Array<AuthorDto>;
    /**
     * The GR/SG link to the book page.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'url': string;
    /**
     * The list of genres for the book.
     * @type {Array<string>}
     * @memberof StorygraphBookDto
     */
    'genres': Array<string>;
    /**
     * The name of the series, if the book belongs to any.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'series': string;
    /**
     * The SG link to the cover of the book.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'coverUrl': string;
    /**
     * The average rating of the book.
     * @type {number}
     * @memberof StorygraphBookDto
     */
    'avgRating': number;
    /**
     * The trigger warnings for the book.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'warnings': string;
    /**
     * The moods for the book.
     * @type {Array<string>}
     * @memberof StorygraphBookDto
     */
    'moods': Array<string>;
    /**
     * The paces for the book.
     * @type {Array<string>}
     * @memberof StorygraphBookDto
     */
    'pace': Array<string>;
    /**
     * The set of question answer pairs for the book.
     * @type {Array<QuestionAnswerDto>}
     * @memberof StorygraphBookDto
     */
    'quesAns': Array<QuestionAnswerDto>;
    /**
     * The description or blurb of the book.
     * @type {string}
     * @memberof StorygraphBookDto
     */
    'description': string;
}

