/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateUserDtoProfile } from './create-user-dto-profile';

/**
 * 
 * @export
 * @interface UpdateUserDto
 */
export interface UpdateUserDto {
    /**
     * The unique ID for the user.
     * @type {string}
     * @memberof UpdateUserDto
     */
    'userId'?: string;
    /**
     * The username.
     * @type {string}
     * @memberof UpdateUserDto
     */
    'name'?: string;
    /**
     * The joining date for the user.
     * @type {string}
     * @memberof UpdateUserDto
     */
    'joinDate'?: string;
    /**
     * 
     * @type {CreateUserDtoProfile}
     * @memberof UpdateUserDto
     */
    'profile'?: CreateUserDtoProfile;
}

