/* tslint:disable */
/* eslint-disable */
/**
 * OWS
 * API description for the Organized Web Server
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CreateEventDtoDates } from './create-event-dto-dates';
// May contain unused imports in some cases
// @ts-ignore
import { CreateEventDtoRequestedBy } from './create-event-dto-requested-by';
// May contain unused imports in some cases
// @ts-ignore
import { Participant } from './participant';

/**
 * 
 * @export
 * @interface UpdateEventDto
 */
export interface UpdateEventDto {
    /**
     * The name of the event.
     * @type {string}
     * @memberof UpdateEventDto
     */
    'name'?: string;
    /**
     * The object ID of the book document.
     * @type {string}
     * @memberof UpdateEventDto
     */
    'book'?: string;
    /**
     * A list of channel/thread IDs.
     * @type {Array<string>}
     * @memberof UpdateEventDto
     */
    'threads'?: Array<string>;
    /**
     * The status of the event.
     * @type {string}
     * @memberof UpdateEventDto
     */
    'status'?: UpdateEventDtoStatusEnum;
    /**
     * The type of the event.
     * @type {string}
     * @memberof UpdateEventDto
     */
    'type'?: UpdateEventDtoTypeEnum;
    /**
     * 
     * @type {CreateEventDtoDates}
     * @memberof UpdateEventDto
     */
    'dates'?: CreateEventDtoDates;
    /**
     * 
     * @type {CreateEventDtoRequestedBy}
     * @memberof UpdateEventDto
     */
    'requestedBy'?: CreateEventDtoRequestedBy;
    /**
     * A list of participants who show interest in the event.
     * @type {Array<Participant>}
     * @memberof UpdateEventDto
     */
    'interested'?: Array<Participant>;
    /**
     * The participants who read the book in the event duration.
     * @type {Array<Participant>}
     * @memberof UpdateEventDto
     */
    'readers'?: Array<Participant>;
    /**
     * The participants who lead the discussion for the event.
     * @type {Array<Participant>}
     * @memberof UpdateEventDto
     */
    'leaders'?: Array<Participant>;
    /**
     * The description of the event.
     * @type {string}
     * @memberof UpdateEventDto
     */
    'description'?: string;
}

export const UpdateEventDtoStatusEnum = {
    Requested: 'Requested',
    Approved: 'Approved',
    Announced: 'Announced',
    Ongoing: 'Ongoing',
    Completed: 'Completed',
    Rejected: 'Rejected',
    Cancelled: 'Cancelled'
} as const;

export type UpdateEventDtoStatusEnum = typeof UpdateEventDtoStatusEnum[keyof typeof UpdateEventDtoStatusEnum];
export const UpdateEventDtoTypeEnum = {
    BuddyRead: 'BuddyRead',
    MonthlyRead: 'MonthlyRead',
    ShortStoryRead: 'ShortStoryRead',
    PoetryRead: 'PoetryRead',
    Other: 'Other'
} as const;

export type UpdateEventDtoTypeEnum = typeof UpdateEventDtoTypeEnum[keyof typeof UpdateEventDtoTypeEnum];


